# update_amazon_linux/tasks/main.yml
---
- name: Update all system packages
  dnf:
    name: "*"
    state: latest

    - name: Reboot the server if the kernel was updated
    reboot:
    msg: "Rebooting the server due to kernel update"
    reboot_timeout: 600
    when: ansible_facts.packages|flatten|select('regex', '^kernel$') is any
    #when: "'kernel' in ansible_facts.packages"

- name: Wait for the server to come back online
  wait_for_connection:
    timeout: 300

